# -*- coding:utf-8 -*-
#+LANGUAGE:  zh
#+TITLE:     纪秀峰_个人简历(Java)
#+AUTHOR:    纪秀峰
#+EMAIL:     jixiuf@gmail.com
#+DATE:     2012-03-14 三
#+DESCRIPTION:个人简历
#+KEYWORDS: 个人简历
#+OPTIONS:   H:2 num:nil toc:nil \n:t @:t ::t |:t ^:nil -:t f:t *:t <:t
#+FILETAGS:
* Word 版简历
+  [[file:download/JiXiufeng_Java_Web.doc][纪秀峰_Java.doc]]
* 基本信息
  |------------+--------------------|
  | 电    话   | 13522419247　      |
  | 出生年月   | 1989-01            |
  | E-mail     | jixiuf@qq.com　    |
  | 英语水平   | 六级460            |
  | 证    书   | 数据库三级         |
  | 毕业院校   | 青岛科技大学       |
  | 学    历   | 本科 2007-9~2011-7 |
  | 户口所在地 | 山东青岛           |
  | 现居住地   | 北京海淀区         |
* 择业目标：
  + Java程序员　    基于Web应用的Java软件开发。
* 自我介绍：
csdn博客：            http://blog.csdn.net/jixiuffff
个人主页:              http://jixiuf.github.com/sitemap.html
EmacsWiki个人主页：  http://emacswiki.org/Joseph
自学能力强，所有计算机知识均为自学。以上几个网址是个人成果的展示，
EmacsWiki个人主页:为我为Emacs开源社区贡献的代码。
* 专业技能：
+ 精通基于Web应用的JAVA编程： JSP/Servlet JSTL JDBC ；
+ 精通Struts1 Struts2 Hibernate Spring(AOP,IOC)等框架的使用；
+ 熟悉JPA EJB3 JMS  JavaMail的使用。
+ 熟练使用Lucene Compass 等Java搜索相关框架的使用及与 Hibernate Spring 框架的整合。
+ 熟练使用SVN、 Git等版本管理工具；
+ 熟练使用Maven Nexus 对项目进行管理；
+ 熟练在基于Windows, Linux(Gentoo，redhat) 环境下进行Java软件开发,偏爱Linux；
+ 掌握基于Oracle的数据库编程：JDBC 、 PLSQL；
+ 熟练掌握Html JavaScript/AJAX Jquery客户端代码的编写;了解Extjs、 Flex、 DWR  的使用;
+ 熟练使用MyEclipse,Eclipse ,等 集成IDE工具,及Linux  下Vim、Emacs 编辑器；
+ 熟练应用多种JAVA服务器,包括 JBoss，Apache Tomcat ；
* 开发经验：
**      海华生产管理系统(2011-7~2011-11)
    为青岛海华纤维有限公司（主要生产假发的半成品）编写生产管理系统 。主要分为三大模块：
1. 数据收集模块主要通过PDA(掌上电脑)条码扫描器从各袋半制品上的条码上扫描得到数
      据(进行盘点)、以及进行入库、出库操作。
2. PC 端，也同时可以进行入库、出库、数据统计、盘点、条形码打印等操作。PC端 主要
      使用C#、Silverlight WCF 等技术，后台数据库用SQL Server 2008。 前台界面使
      用Silverlight模仿Window7 操作系统，主要实现了用户权限控制、半制品（分为4
      个类似模块:半制品仓库、中间仓库、灌壁仓库、粉碎丝仓库）分别有入库、出库、
      统计、盘点等功能。
3. 条形码的生成通过调用TSC dll的打印功能实现。打印模块各独做成一个服务，放在服
      务器上，无论是扫描器端 、还是PC端都可以远程调用打印机进行条形码的打印
4. 我主要负责的tsc条码打印服务的编写、及条形码扫描器端3个出库画面、半制品盘点、
   灌壁盘点)(灌壁入库)、 等多个画面。PC端负责1个盘点画面(半制品盘点)、3个出库画
   面(中间仓库出库、灌壁出库、 粉碎丝出库、)、及半制品的管理(新增、更新、冻结、
   初始化库存)等操作。

**   修改并完善 Eclipse插件 EasyExplore (在校期间)
     easyExplore 是一个开源项目，主要实现了用文件管理器打开在eclipse中选中的目
录,不过已经停止开发了。而我下载了它的源代码后添加了两项功能，一是添加了用系统编
辑器编辑eclipse中选中的文件，当编辑完这个文件、关闭编辑器时,eclipse会刷新整个项
目并重新编译，以实现eclipse项目同文件系统上文件的同步;另一个功能是在选中的目录
处打开Linux的终端模拟器或者Windows的cmd.exe窗口，可以通过工具栏、右键、快捷键进
行操作。源代码使用Git进行版本控制,托管在
http://github.com/jixiuf/easyexplore_modify_by_jixiuf。
**  DRP分销资源管理系统
       该项目使企业具有对订单和供货具有快速反应和持续补充库存的能力。主要包括分
销库存管理，统计报表管理、基础数据管理、分销费管理、付款结算管理等几个模块。我
主要参与了其中基础数据的管理，分销商库存管理及部分报表的生成。采用Tomcat +
Oracle+Struts2+Hibernate+Spring+JQuery平台，前期在Gentoo Linux平台上进行开发，
后期过程中要用到jacob 通过jni调用生成Word文档形式的报表 ,此部分在Windows XP 系
统上做了测试,另外使用了JFreeChart报表工具生成柱状图饼图等。库存管理。 系统启用
后，主要就是物料的出入库、库存调整过程。后者的操作步骤为：商务主管收集流向单；
数据录入员录入流向单数据；商务主管审核（如 有数量差异，可以修改调整项数据） ；
商务经理审核确认（如果有问题 ，驳回，正确的话就直接冲减库存）。整个系统界面通过
伸缩菜单进行管理（使用jquery自己实现）。源代码托管
在: https://github.com/jixiuf/drp
开发环境：
Gentoo Linux ,Windows XP
JAVA应用服务器： Tomcat；
开发语言及技术： Jsp,Struts2 , Hibernate ,Spring,JQuery；
数据库：Oracle10g。
